server:
  port: 18025

spring:
  application:
    name: redis-vector-demo
  data:
    redis:
      host: localhost
      port: 6380
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      embedding:
        options:
          model: text-embedding-v4
          dimensions: 1024
    vectorstore:
      redis:
        initialize-schema: true
        index-name: saa-vector-index
        prefix: "saa:"
