server:
  port: 18143

spring:
  application:
    name: office-a2a-client
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus
          temperature: 0.3
    alibaba:
      a2a:
        nacos:
          server-addr: 127.0.0.1:8848
          namespace: public
          username: nacos
          password: nacos
          discovery:
            enabled: true
        client:
          card:
            name: inventory-agent
