server:
  port: 18027

spring:
  application:
    name: rag-demo
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus
      embedding:
        options:
          model: text-embedding-v4
          dimensions: 1024
    vectorstore:
      milvus:
        client:
          host: localhost
          port: 19530
          username: root
          password: milvus
        database-name: default
        collection-name: saa_rag_naive
        embedding-dimension: 1024
        index-type: IVF_FLAT
        metric-type: COSINE
        initialize-schema: true
